add wall commit KSU only when CONFIG_KSU is enabled from 3 commit
- fs: Backport path_umount for KernelSu
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>

commit : 922f0470132ae73e2600de00576210ecc375ed50

- BACKPORT: seccomp: add filter_count field for KernelSU
KernelSU requires struct seccomp to have atomic_t filter_count ,
but this field is missing on NON-GKI kernels.

Adding the field fixes build errors such as:
error: no member named 'filter_count' in 'struct seccomp'

Reference: tiann/KernelSU#2708
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>

commit : 44ad45cdbade359b2b438cfa742a33f6829abc71

- selinux: Allow init exec ksud under nosuid
It whitelists init → ksud exec, bypassing nosuid restrictions, to allow su-daemon functionality.

Signed-off-by: prabhatkrmishra <mprabhat774@gmail.com>

commit : b898128acc5a8449d0ad00986b46b949aa810099